name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: apt install libprotobuf-dev protobuf-compiler
      - name: Create build directory
        run: mkdir build
      - name: Run CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release ..
        working-directory: build
      - name: Build onnx2c and tests
        run: make
        working-directory: build
      - name: Run tests
        run: make test
        working-directory: build
